spring:
  application:
    name: url-shortener-metrics
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: io.myzticbean.sharedlibs.dto.model.request.AddMetricsRequest
        spring.json.trusted.packages: '*'

server:
  port: 8081

url-shortener-metrics-api:
  kafka-topic: add-metrics
  geoIpDb-location: classpath:GeoIPDB/GeoLite2-City.mmdb