version: "3.8"

services:
  url-shortener-api:
    build: ./url-shortener-api  # Path to your Dockerfile for the API service
    ports:
      - "8090:8090"  # Map container port 8080 to host port 8080

  url-shortener-db-service:
    build: ./url-shortener-db-service  # Path to your Dockerfile for the DB service
    ports:
      - "8082:8082"  # Map container port 8082 to host port 8082

  url-shortener-metrics:
    build: ./url-shortener-metrics  # Path to your Dockerfile for the metrics service
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081
